@baseUrl = http://localhost:3000/api

### GET /types
GET {{baseUrl}}/types

### GET /places
GET {{baseUrl}}/places

### POST /episodes
POST {{baseUrl}}/episodes

### POST /episodes
POST {{baseUrl}}/episodes
Content-Type: application/json

{
"title": "Some episode title",
"description": "This is a description"
}







# GET http://localhost:4000/types

# ###
# GET http:/localhost:4000/places

# ###
# GET http:/localhost:4000/episodes